name: AutoDeploy
description: Deploying the app to the server
on:
  workflow_dispatch:
jobs:
  compile-jar:
    name: Building jar
    runs-on: ubuntu-latest
    steps:
      - name: Checking repository
        uses: actions/checkout@v2
      - name: Setting up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Building Jar with Maven
        run: mvn --batch-mode clean package
      - name: Moving to the app folder
        run: mkdir deploy && mkdir deploy/DAS && mv target/DAS.war deploy/ && mv DAS/resources deploy/DAS/resources && mv DAS/ssl-server.jks deploy/DAS/ssl-server.jks
      - name: Uploading App to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: App
          path: deploy/*
  deploy:
    name: Deploying to the server
    needs: compile-jar
    runs-on: ubuntu-latest
    steps:
      - name: Downloading App
        uses: actions/download-artifact@v2
        with:
          name: App
      - name: Deploying to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "deploy/*"
  restart:
    name: Restarting the bot
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Restarting bot
        uses: supercrafter100/Pterodactyl-Restart@v1.0
        with:
          PTE_PANEL_URL: ${{ secrets.PTERO_URL }}
          PTE_BEARER_TOKEN: ${{ secrets.PTERO_SECRET }}
          PTE_PANEL_ID: ${{ secrets.PTERO_SERVER_ID }}